[package]
name = "rgb_node"
description = "RGB node"
version = "0.1.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "layer-2", "smart-contracts", "rgb"]
edition = "2018"
readme = "README.md"

[lib]
name = "rgb"

[dependencies]
dotenv = "~0.15"
clap = "=3.0.0-beta.1"
chrono = { version = "~0.4", features = [ "serde" ] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
bech32 = "~0.7"
log = { version = "~0.4", features = ["max_level_trace", "release_max_level_debug"] }
async-trait = "~0.1"
regex = "~1.3"
env_logger = "~0.7"
num-traits = "~0.2"
num-derive = "~0.3"
diesel = { version = "~1.4", features = ["postgres", "uuid", "numeric", "chrono"] }
tokio = { version = "~0.2", features = ["full"] }
futures = "~0.3"
zmq = "~0.9"
tiny_http = "~0.6"
prometheus = "~0.8"
derive_wrapper = "~0.1"
# TODO: Move this dependency to LNP/BP core library
lightning-invoice = { git = "https://github.com/LNP-BP/rust-lightning-invoice.git" }

[dependencies.lnpbp]
git = "https://github.com/lnp-bp/rust-lnpbp"
branch = "develop"
features = ["all"]

[features]
service = []
daemon = ["service"]
cli = []
fungibles = []
collectibles = []
identities = []

[workspace]
members = ["ffi"]
